const answers = [
    'Outlook good',
    'It is decidedly so',
    'Without a doubt',
    'Yes, definitely',
    'You may rely on it',
    'As I see it, yes',
    'Yes', 
    'Signs point to yes',
    'My reply is yes',  
    'My sources say yes',  
    'Count on it',  
    'Absolutely',
    'Yes! Break out the sparkling cider!',
    'So let it be written. So let it be done.',
    'It is certain',
    'Great question! Yes!',
    'A thousand times yes!',
    'The answer is yes',
    'Go for it!',
    'You can count on it',
    'The outlook is good',
    'Of course!',
    'The stars say yes',
    'The universe says yes',
    'The answer is yes',
    'Definitely',
    'You can do it!',
    'Yes, you can!',
    'Yes, in due time',
    'Yes, it\'s your lucky day!',
    'Yes, for sure!',
    'Very well.',
    'By all means, yes!',
    'Yes, yes, yes!',
    'Yes, enjoy!',
    'Yes, you will!',
    'Yep!',
    'Yes, yes, yes, yes, yes!',
    'You bet!',
    'For sure!',
    'Fo sho!',
    'Heck, yes!',
    'Assuredly',
    'Indisputably yes',
    'Undoubtedly yes',
    'Unquestionably yes',
    'Unmistakably yes',
    'Unerringly yes',
    'Unfailingly yes',
    'Aye aye captain',
    'Totally!',
    'Yes sir',
    'Yes siree',
    'Yuppers',
    'Indubitably',
    'Yes, and how!',
    'Yes, and amen!',
    'Sure thing',
    'You betcha',
    'You got it',
    'You\'re on',
    'You\'re on like Donkey Kong',
    'Yes, permission granted.',
    'Yes, you\'ve got a point there.',
    'Totes',
    'Totally!',
    'Thumbs up',
    'Affirmative',
    '👌',
    'Two thumbs up!',
    '👍',
    '👍👍',
    'You were born for it!',
    'Do fish swim?',
    'Do fish swim? 🐟',
    'Even my dog is saying yes',
    'Even my dog is saying yes 🐶',
    'Right on the money!',
    'Right on the money! 💰',
    'I give you my blessing',
    'What\'s the opposite of no?',
    'Is the sun hot?',
    'Is the sun hot? ☀️',
    'Do vacuum cleaners suck?',
    'Follow your heart',
    'Follow your heart 💗',
    'Go on!',
    'I agree to the fullest!',
    'I can\'t argue with that!',
    'I couldn\'t agree more',
    'A thousand times, yes!',
    'Your wish is my command',
    '100% yes',
    'Right on, brother',
    'Right on, sister',
    'Great idea!',
    'No worries',
    'You deserve a standing ovation for that idea.',
    'Yes, my liege',
    'The answer is a resounding yes!',
    'Life\'s too short to be saying no.',
    'Make it work!',
    'Totes',
    'Darn straight',
    'You get my vote',
    'I subscribe to your idea.',
    'You deserve a round of applause',
    'What are you waiting for?',
    `Give me a 'Y.' Give me an 'E.' Give me an 'S.' Give me a 'Y-E-S!'`,
    'The deal is on!',
    'I give you my seal of approval',
    'My 2 thumbs are standing in salute.',
    'I\'m all for it!',
    'I would like to express my full approval',
    'I gladly concur',
    'My answer is in the affirmative',
    'You got it, chief!',
    'Yes, I thought you\'d never ask',
    'By all means, go for it!',
    'Count me in!',
    'Sounds good!',
    'Bring it!',
    'Let\'s go!',
    'A million times yes!',
    'Preach!',
    'Preach it!',
    'Oh yeah, baby!',
    'Good idea!', 
    'Great idea!',
    'Brilliant idea!',
    'Awesome idea!',
    'Perfect!',
    'Chase your dreams!',
    'Make it happen!',
    'Make a plan and make it happen!',
    'I think so!',
    'I believe so!',
    'Why not?',
    'What do you have to lose?',
    'Give it a try!',
    'It\'s worth a shot!',
    'Just do it!',
    'Small steps!',
    'Never give up!',
    'Stay strong!',
    'Keep pushing!',
    'Keep fighting!',
    'I\'m rooting for you!',
    'I\'m cheering for you!',
    'I\'m behind you 100%!',
    'I\'m behind you all the way!',
    'Reach for the stars!',
    'Believe in yourself!',
    'The sky is the limit!',
    'Don\'t stress; you got this!',
    'Good luck! I know you are going to do great!',
    'I know you are going to do great!',
    'I\'m so proud of you!',
    'Yes, sending good vibes and happy thoughts your way!',
    'Yes, courage, strength, and confidence are yours!',
    'You can change the world!',
    'Don\'t be afraid to try!',
    'Yes, no one else is you, and that is your superpower!',
    'Yes, you are stronger than you think you are!',
    'Yes, you are braver than you think you are!',
    'Yes, your speed doesn\'t matter, it\'s your direction that counts!',
    'Yes, you are a winner!',
    'Yes, you are capable of more than you know!',
    'Yes, you are a force to be reckoned with!',
    'Yes, I can\'t wait to see what you do next!',
    'Yes, you should be so proud of yourself!',
    'Yes, you can do anything you set your mind to!',
    'Yes, make today matter!',
    'Yes, embrace every challenge!',
    'Yes, embrace every moment!',
    'Yes, and remember to be the best version of yourself!',
    'Yes, and remember to be kind to yourself!',
    'Yes, and remember to be positive, patient, and persistent!',
    'Yes, and remember to be grateful!',
    'Yes, and keep going until you are proud',
    'Yes, and remember to give yourself some credit for all you\'ve done so far!',
    'YES!',
    'YES! YES! YES!',
    'Yes, you are amazing!',
    'Yes, you are awesome!',
    'Yes, I shake you warmly by the hand!',
    'Yes, I shake you warmly by the hand! 🤝',
    'Yes, tremendous things are in store for you!',
    'Yes, many wonderful surprises await you!',
    'This chapter of your life is going to be so amazing!',
    'Keep up the good work!',
    'Yes, the world is definitely better with you in it!',
    'I have faith in you!',
    'Trust your instincts',
    'Your ideas are worthwhile',
    'You are capable',
    'Your choices matter',
    'You can make a difference',
    'You are learning',
    'You are growing',
    'You are valuable',
    'You are interesting',
    'You\'ve made me think of things in a completely new way.',
    'I\'m excited to see what you do',
    'You are unique!',
    'You are gifted!',
    'You are so thoughtful',
    'You are intelligent',
    'Just keep going and keep trying!',
    'Yes, and remember: you can ask for help',
    'Yes, and remember: you can ask for help!',
    'You are unstoppable!',
    'Have fun!',
    'Enjoy the journey!',
    'Enjoy the moment!',
    'You are one smart cookie!',
    'I believe you; I believe in you!',
    'You inspire me!',
    'There\'s greatness in your future; I know it.',
    'You are a gift to those around you!',
    'You are a gift to those around you! 🎁',
    'The best is yet to come! Trust in the process.',
    'Your life is your message to the world. Make it inspiring.',
]   

const ball = document.getElementById('ball')
const ballAnswerContainer = document.getElementById('ball-answer-container')
const ballAnswer = document.getElementById('ball-answer')
const formEl = document.getElementById('question-form')

ball.addEventListener('click', ()=> {
    handleShake()
})

formEl.addEventListener('submit', (e)=> {
    e.preventDefault()
    handleShake()
})

function handleShake() {
    ball.classList.add('shake')
    setTimeout(()=> {
        ball.classList.remove('shake')
        ballAnswerContainer.classList.add('bg-gradient-to-b', 'from-blue-600', 'to-blue-800')
        ballAnswer.classList.remove('text-9xl', 'text-black')
        ballAnswer.classList.add('text-xs', 'text-center')
        ballAnswer.textContent = answers[Math.floor(Math.random() * answers.length)]
    }, 1500)
}

const hamburgerBtn = document.getElementById("mobile-menu-button")
const mobileMenu = document.querySelector(".mobile-menu")

hamburgerBtn.addEventListener("click", () => {
        mobileMenu.classList.toggle("hidden")
})

function getCurrentYear() {
const currentYear = new Date().getFullYear()
document.getElementById('current-year').textContent = currentYear
}

getCurrentYear()
        